name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: '& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AfJohXkd4Lgj1_hn_ST52pO1W5_d_YIOzc2t8hpVEAEAuN4Cv-GltGHGGJlYKxyeXs4iXg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME'
        required: user
      pincode:
        description: 'Six digit Pin'
        required: 615792
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
